SATFFING PROJECT
The main purpose of this project is to predict the staff needed to work in an hotel in Glasneeving area, this predictions are going to be based on historical Weather, events and ocupancy from the hotel. This predictions will impact to prevent overstaffing and understafing, generating a better distribution of staff, improving customer service and avoiding the waste on salaries.

WEATHER DATA SET
In this section I imported 3 data sets from MEt Eireann, from 2023, 2024 and 2025, It contains information like rain, max temperature, min temprerature and date, those 4 are the features I need to determin "How a good weather look like". I merged the 3 data sets and I defined this 3 parameters, 1 Good/Warm, 2 Dry/Cool, 3 Poor/Wet.

In [1]:
#Important libraries 
import pandas as pd
import numpy as np

In [2]:
#Import the 3 data sets from Met Eireann, the sets are clean and organized, the main task here is to merge them and create the conditionals that
#will determine how a good weather looks like to impact the hotel ocupancy
df_23 = pd.read_csv("DataSets/dly1823_subset 2023.csv", skiprows=13)
df_24 = pd.read_csv("DataSets/dly1823_subset2024.csv", skiprows=13 )
df_25 = pd.read_csv("DataSets/dly1823_subset 2025.csv", skiprows=13)

#Combine into one master weather dataframe, 
df = pd.concat([df_23, df_24, df_25], ignore_index=True)


# Preview the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1065 entries, 0 to 1064
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1065 non-null   object
 1   ind     1065 non-null   int64
 2   rain    1065 non-null   float64
 3   ind.1   1065 non-null   int64
 4   maxt    1065 non-null   float64
 5   ind.2   1065 non-null   int64
 6   mint    1065 non-null   float64
 7   gmin    1065 non-null   object
 8   soil    1065 non-null   object
dtypes: float64(3), int64(3), object(3)
memory usage: 75.0+ KB

In [3]:
df.head

<bound method NDFrame.head of              date  ind  rain  ind.1  maxt  ind.2  mint  gmin soil
0        1-Jan-23    0   0.4      0   7.2      0   2.5   1.4
1        2-Jan-23    0   0.8      0  10.9      0   1.9  -1.7
2        3-Jan-23    0   0.6      0  14.4      1  -0.5  -4.4
3        4-Jan-23    0   0.2      0  12.9      0   9.4   8.2
4        5-Jan-23    0   1.8      0  13.7      0   9.6   6.4
...           ...  ...   ...    ...   ...    ...   ...   ...  ...
1060  26-nov-2025    0   0.8      0  14.6      1  -1.0  -4.5
1061  27-nov-2025    0   7.7      0  16.0      0   8.8   3.0
1062  28-nov-2025    0   1.7      0   9.2      0   6.5   3.2
1063  29-nov-2025    0   4.1      0   6.9      0   2.3  -3.9
1064  30-nov-2025    0   9.2      0  12.4      0   0.2  -5.0

[1065 rows x 9 columns]>

In [4]:
df_filtered = df [["date", "rain", "maxt", "mint"]] #Now I'll filter only the freatures that impact my model.
df_filtered.head()

       date  rain  maxt  mint
0  1-Jan-23   0.4   7.2   2.5
1  2-Jan-23   0.8  10.9   1.9
2  3-Jan-23   0.6  14.4  -0.5
3  4-Jan-23   0.2  12.9   9.4
4  5-Jan-23   1.8  13.7   9.6

In [5]:
conditions = [
    #Good/Warm: Less than 1mm rain AND 16C or warmer
    (df_filtered['rain'] < 1.0) & (df_filtered['maxt'] >= 13),
    
    #Dry/Cool: Less than 1mm rain AND cooler than 16C
    (df_filtered['rain'] < 1.0) & (df_filtered['maxt'] < 13),
    
    #Poor/Wet: 5mm+ of rain OR very cold (under 5C max)
    (df_filtered['rain'] >= 5.0) | (df_filtered['maxt'] < 8),
]

choices = ['Good/Warm', 'Dry/Cool', 'Poor/Wet']

# Apply the choices, everything else becomes 'Moderate/Changeable'
df_filtered['weather_quality'] = np.select(conditions, choices, default='Moderate/Changeable')


df_filtered.head(10)
df_filtered = df_filtered.copy()

C:\Users\NHLUJ\AppData\Local\Temp\ipykernel_13900\1700589811.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['weather_quality'] = np.select(conditions, choices, default='Moderate/Changeable')

DUBLIN EVENTS DATA SET 
This data set was created with the help of AI to find all the past events from 2023 to 2025 that can impact the Glasneevin area. This data set will help to predict the events that can impact the hotel occupancy. 
I specifically created the list of events with the "date" column in the same format than wetaher data set, so I can merge them together.

In [6]:
df_events = pd.read_csv("DataSets/dublin_events_2023_2025.csv")
df_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          34 non-null     object
 1   event_impact  34 non-null     int64
 2   event_name    34 non-null     object
dtypes: int64(1), object(2)
memory usage: 948.0+ bytes

In [7]:
df_events.head(10) #first overview of the data set

        date  event_impact                                         event_name
0  11-Feb-23             1                     Six Nations: Ireland vs France
1  17-Mar-23             2                         St. Patrick's Day Festival
2  18-Mar-23             1                    Six Nations: Ireland vs England
3   5-May-23             2                          Bruce Springsteen Concert
4   7-May-23             2                          Bruce Springsteen Concert
5   9-May-23             2                          Bruce Springsteen Concert
6  20-May-23             1               Heineken Champions Cup Final (Aviva)
7  23-Jul-23             2      All-Ireland Senior Hurling Final (Croke Park)
8  30-Jul-23             2     All-Ireland Senior Football Final (Croke Park)
9  26-Aug-23             1  College Football Classic: Notre Dame vs Navy (...

In [8]:
df_filtered['date'] = pd.to_datetime(df_filtered['date']) # I can see all the rows share the same date format so now i can merge based on that
df_events['date'] = pd.to_datetime(df_events['date'])
df_merged = pd.merge(df_filtered, df_events, on= "date", how="left")

C:\Users\NHLUJ\AppData\Local\Temp\ipykernel_13900\3606911853.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_filtered['date'] = pd.to_datetime(df_filtered['date']) # I can see all the rows share the same date format so now i can merge based on that
C:\Users\NHLUJ\AppData\Local\Temp\ipykernel_13900\3606911853.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_events['date'] = pd.to_datetime(df_events['date'])

In [9]:
df_merged['event_impact'] = df_merged['event_impact'].fillna(0) # on the df the days that we dont have events should be marked as 0
df_merged['event_name'] = df_merged['event_name'].fillna('No Event') # and the name as No event, insted of just saying NAN
df_merged.head()
#Event impact 0 means no event, and 1 means we have an event that can impact the bussiness

        date  rain  maxt  mint      weather_quality  event_impact event_name
0 2023-01-01   0.4   7.2   2.5             Dry/Cool           0.0   No Event
1 2023-01-02   0.8  10.9   1.9             Dry/Cool           0.0   No Event
2 2023-01-03   0.6  14.4  -0.5            Good/Warm           0.0   No Event
3 2023-01-04   0.2  12.9   9.4             Dry/Cool           0.0   No Event
4 2023-01-05   1.8  13.7   9.6  Moderate/Changeable           0.0   No Event

THE HOTEL DATA SET
This data set contains a data set obtained from Kaggle, based on the first overview I can see that the data corresponds to a different year that I am not focus on, so since this is not a real data set, instead of finding one that belongs to 2023, 2024, and 2025, I'll modify the years to match my events and weather data sets. 
This data set contains many columns that are not align with my other data sets so I'll unify them to try to match dates.

In [10]:
df_hotel = pd.read_csv("DataSets/hotel_bookings.csv")
df_hotel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [11]:
df_hotel.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [12]:
df_hotel_clean = df_hotel.copy() #I create a copy so I don't mess up the original

# Manually replace each year one by one, this data set do not contain real information and do not belong to the time/years I an trying to use for my machine
#learning, so I changed the years to 2023,2024 and 2025 to match my event and weather data sets.  
df_hotel_clean['arrival_date_year'] = df_hotel_clean['arrival_date_year'].replace(2015, 2023)
df_hotel_clean['arrival_date_year'] = df_hotel_clean['arrival_date_year'].replace(2016, 2024)
df_hotel_clean['arrival_date_year'] = df_hotel_clean['arrival_date_year'].replace(2017, 2025)

# Show the first few rows to prove it worked
df_hotel_clean[['hotel', 'arrival_date_year']].head(10)

          hotel  arrival_date_year
0  Resort Hotel               2023
1  Resort Hotel               2023
2  Resort Hotel               2023
3  Resort Hotel               2023
4  Resort Hotel               2023
5  Resort Hotel               2023
6  Resort Hotel               2023
7  Resort Hotel               2023
8  Resort Hotel               2023
9  Resort Hotel               2023

In [13]:
print("Hotels found in data:", df_hotel_clean['hotel'].unique()) #I can see the set contain more than one hotel, I'll get rid onf one

Hotels found in data: ['Resort Hotel' 'City Hotel']

In [14]:
df_single_hotel = df_hotel_clean[df_hotel['hotel'] == 'City Hotel'].copy() # I choose to stay with City Hotel

In [15]:
print("Hotels found in data:", df_single_hotel['hotel'].unique()) # Now I can confirm I only have one hotel to analyse

Hotels found in data: ['City Hotel']

In [16]:
 print(df_single_hotel['arrival_date_year'].unique()) #And I just confirm I have data on the years I need

[2023 2024 2025]

In [17]:
#By looking at the columns I can see that the information I need is in "adults", I only focus on how many people stayed per nigth and I'll include "kids" too
df_single_hotel["total_people"] = df_single_hotel["adults"] + df_single_hotel["children"].fillna(0)

In [18]:
#I mapped the months, since on the data set they have different formatting, I have to reset the dates to make them fit with my other sets
month_map= {"January":1, "February":2, "March":3, "April":4, "May":5, "June":6, 
             "July":7, "August":8, "September":9, "October":10, "November":11, "December":12}
df_single_hotel["month_num"] = df_single_hotel["arrival_date_month"].map(month_map)

In [19]:
df_single_hotel['date'] = pd.to_datetime({ # now combine year, month and day in to my df
    "year": df_single_hotel["arrival_date_year"],
    "month": df_single_hotel["month_num"],
    "day": df_single_hotel["arrival_date_day_of_month"]
})

In [24]:
df_occupancy = df_single_hotel.groupby('date')['total_people'].sum().reset_index()
#now that the 
df_occupancy.rename(columns={'total_people': 'occupancy'}, inplace=True) #I renamed the column to make it clear 
df_occupancy["occupancy"] = df_occupancy["occupancy"].fillna(0)
df_occupancy.head(10)

        date  occupancy
0 2023-07-01      143.0
1 2023-07-02       96.0
2 2023-07-03       28.0
3 2023-07-04       72.0
4 2023-07-05       15.0
5 2023-07-06       58.0
6 2023-07-07       35.0
7 2023-07-08       79.0
8 2023-07-09       92.0
9 2023-07-10       19.0

FINAL MERGE : So at this point I have 3 data sets, df_occupancy from the hotel, df_merged that contains weather and events data sets, its time to create a mega final merge to combine all the information we need to start our analysis;
I identified a missmatch on the starting dates, the data set from Met Eireann starts from January whereas the data set fromt the hotel occupancy starts from July. To ensure the Random Forest model is trained with the best quality, I removed the initial 6 months where the occupancy was missing.

In [27]:
df_final = pd.merge(df_merged, df_occupancy, on= "date", how="left") #Finla merge of data sets

In [30]:
print("3 Data sets integrated: ", df_final.columns.tolist()) #
# Turn the NaNs into 0.0
df_final['occupancy'] = df_final['occupancy'].fillna(0)
df_final.head(35)

3 Data sets integrated:  ['date', 'rain', 'maxt', 'mint', 'weather_quality', 'event_impact', 'event_name', 'occupancy']

,date,rain,maxt,mint,weather_quality,event_impact,event_name,occupancy
0,2023-01-01,0.4,7.2,2.5,Dry/Cool,0.0,No Event,0.0
1,2023-01-02,0.8,10.9,1.9,Dry/Cool,0.0,No Event,0.0
2,2023-01-03,0.6,14.4,-0.5,Good/Warm,0.0,No Event,0.0
3,2023-01-04,0.2,12.9,9.4,Dry/Cool,0.0,No Event,0.0
4,2023-01-05,1.8,13.7,9.6,Moderate/Changeable,0.0,No Event,0.0
5,2023-01-06,3.1,12.3,6.9,Moderate/Changeable,0.0,No Event,0.0
6,2023-01-07,0.8,10.7,7.6,Dry/Cool,0.0,No Event,0.0
7,2023-01-08,0.9,8.4,6.6,Dry/Cool,0.0,No Event,0.0
8,2023-01-09,5.5,13.3,4.4,Poor/Wet,0.0,No Event,0.0
9,2023-01-10,3.5,14.1,5.0,Moderate/Changeable,0.0,No Event,0.0
10,2023-01-11,4.8,12.1,6.6,Moderate/Changeable,0.0,No Event,0.0
11,2023-01-12,2.5,10.4,6.4,Moderate/Changeable,0.0,No Event,0.0
12,2023-01-13,5.1,10.8,6.7,Poor/Wet,0.0,No Event,0.0
13,2023-01-14,1.4,7.7,6.0,Poor/Wet,0.0,No Event,0.0
14,2023-01-15,0.0,5.9,2.8,Dry/Cool,0.0,No Event,0.0
15,2023-01-16,0.0,4.1,-1.0,Dry/Cool,0.0,No Event,0.0
16,2023-01-17,0.0,3.4,-4.4,Dry/Cool,0.0,No Event,0.0
17,2023-01-18,0.0,4.6,-3.3,Dry/Cool,0.0,No Event,0.0
18,2023-01-19,0.0,5.9,-1.9,Dry/Cool,0.0,No Event,0.0
19,2023-01-20,0.0,8.3,-4.0,Dry/Cool,0.0,No Event,0.0
20,2023-01-21,0.8,10.0,-3.2,Dry/Cool,0.0,No Event,0.0
21,2023-01-22,0.1,11.3,7.0,Dry/Cool,0.0,No Event,0.0
22,2023-01-23,0.4,13.0,7.4,Good/Warm,0.0,No Event,0.0
23,2023-01-24,1.1,12.9,3.6,Moderate/Changeable,0.0,No Event,0.0
24,2023-01-25,0.4,10.7,4.3,Dry/Cool,0.0,No Event,0.0
25,2023-01-26,0.0,9.4,4.2,Dry/Cool,0.0,No Event,0.0
26,2023-01-27,0.0,7.8,2.9,Dry/Cool,0.0,No Event,0.0
27,2023-01-28,0.3,8.1,0.1,Dry/Cool,0.0,No Event,0.0
28,2023-01-29,0.0,10.9,4.7,Dry/Cool,0.0,No Event,0.0
29,2023-01-30,0.2,9.8,4.6,Dry/Cool,0.0,No Event,0.0
30,2023-01-31,0.0,10.0,5.9,Dry/Cool,0.0,No Event,0.0
31,2023-02-01,0.0,10.9,6.6,Dry/Cool,0.0,No Event,0.0
32,2023-02-02,0.0,11.2,8.0,Dry/Cool,0.0,No Event,0.0
33,2023-02-03,0.0,13.4,10.0,Good/Warm,0.0,No Event,0.0
34,2023-02-04,0.6,12.0,8.6,Dry/Cool,0.0,No Event,0.0

In [40]:
#I notticed the occupancy is 0 for way to many rows, now I can validate the data sets do not match
#they have different starting points, the best way to adress this can be delete the firs 6 months of the 
#df_merged 
print("weather and events data set", df_merged['date'].min())
print("Hotel data set", df_occupancy['date'].min())

weather and events data set 2023-01-01 00:00:00
Hotel data set 2023-07-01 00:00:00

In [42]:
df_final = df_final[df_final['date'] >= '2023-07-01'].copy() #Again i created a copy beacause it shows an error if I dont do it
df_final = df_final.reset_index(drop=True) # Reset the index so the first row in July is Row 0

df_final.head(50) #Now the date starts from 01/July/20223

,date,rain,maxt,mint,weather_quality,event_impact,event_name,occupancy
0,2023-07-01,0.0,19.4,13.3,Good/Warm,0.0,No Event,143.0
1,2023-07-02,3.2,18.1,11.2,Moderate/Changeable,0.0,No Event,96.0
2,2023-07-03,6.4,18.1,10.6,Poor/Wet,0.0,No Event,28.0
3,2023-07-04,2.5,20.2,10.2,Moderate/Changeable,0.0,No Event,72.0
4,2023-07-05,0.0,18.7,9.9,Good/Warm,0.0,No Event,15.0
5,2023-07-06,0.9,19.6,13.2,Good/Warm,0.0,No Event,58.0
6,2023-07-07,0.0,22.0,15.7,Good/Warm,0.0,No Event,35.0
7,2023-07-08,0.0,22.8,15.7,Good/Warm,0.0,No Event,79.0
8,2023-07-09,3.7,22.2,12.5,Moderate/Changeable,0.0,No Event,92.0
9,2023-07-10,13.0,17.7,12.8,Poor/Wet,0.0,No Event,19.0
10,2023-07-11,1.9,20.7,13.8,Moderate/Changeable,0.0,No Event,121.0
11,2023-07-12,0.0,20.9,13.1,Good/Warm,0.0,No Event,36.0
12,2023-07-13,2.3,20.3,11.9,Moderate/Changeable,0.0,No Event,66.0
13,2023-07-14,16.3,18.8,14.2,Poor/Wet,0.0,No Event,12.0
14,2023-07-15,5.9,16.2,13.7,Poor/Wet,0.0,No Event,84.0
15,2023-07-16,9.7,19.7,12.9,Poor/Wet,0.0,No Event,100.0
16,2023-07-17,6.1,20.0,11.8,Poor/Wet,0.0,No Event,158.0
17,2023-07-18,2.7,19.0,12.8,Moderate/Changeable,0.0,No Event,214.0
18,2023-07-19,1.6,19.4,13.1,Moderate/Changeable,0.0,No Event,12.0
19,2023-07-20,1.3,18.6,12.2,Moderate/Changeable,0.0,No Event,115.0
20,2023-07-21,10.0,19.2,11.5,Poor/Wet,0.0,No Event,76.0
21,2023-07-22,27.0,19.5,13.7,Poor/Wet,0.0,No Event,199.0
22,2023-07-23,2.2,16.3,15.1,Moderate/Changeable,2.0,All-Ireland Senior Hurling Final (Croke Park),174.0
23,2023-07-24,0.3,18.3,10.7,Good/Warm,0.0,No Event,14.0
24,2023-07-25,0.3,20.4,8.1,Good/Warm,0.0,No Event,285.0
25,2023-07-26,8.3,18.0,10.3,Poor/Wet,0.0,No Event,13.0
26,2023-07-27,0.0,23.5,16.2,Good/Warm,0.0,No Event,212.0
27,2023-07-28,0.0,21.4,13.8,Good/Warm,0.0,No Event,21.0
28,2023-07-29,2.8,20.4,13.1,Moderate/Changeable,0.0,No Event,25.0
29,2023-07-30,2.7,18.4,13.5,Moderate/Changeable,2.0,All-Ireland Senior Football Final (Croke Park),95.0
30,2023-07-31,2.9,18.6,15.7,Moderate/Changeable,0.0,No Event,16.0
31,2023-08-01,18.0,20.3,12.7,Poor/Wet,0.0,No Event,67.0
32,2023-08-02,2.0,17.6,13.4,Moderate/Changeable,0.0,No Event,9.0
33,2023-08-03,0.0,20.0,12.3,Good/Warm,0.0,No Event,239.0
34,2023-08-04,46.9,21.1,9.7,Poor/Wet,0.0,No Event,20.0
35,2023-08-05,0.0,17.7,10.9,Good/Warm,0.0,No Event,243.0
36,2023-08-06,9.5,19.1,9.9,Poor/Wet,0.0,No Event,97.0
37,2023-08-07,0.0,19.1,9.0,Good/Warm,0.0,No Event,182.0
38,2023-08-08,0.0,19.0,11.2,Good/Warm,0.0,No Event,304.0
39,2023-08-09,0.3,23.7,12.2,Good/Warm,0.0,No Event,65.0
40,2023-08-10,0.0,23.6,15.0,Good/Warm,0.0,No Event,271.0
41,2023-08-11,0.8,23.0,15.3,Good/Warm,0.0,No Event,128.0
42,2023-08-12,0.0,20.7,16.9,Good/Warm,0.0,No Event,204.0
43,2023-08-13,0.0,20.6,14.6,Good/Warm,0.0,No Event,143.0
44,2023-08-14,0.0,21.0,12.9,Good/Warm,0.0,No Event,560.0
45,2023-08-15,0.0,22.3,13.8,Good/Warm,0.0,No Event,249.0
46,2023-08-16,0.0,19.6,11.8,Good/Warm,0.0,No Event,63.0
47,2023-08-17,1.9,21.4,11.7,Moderate/Changeable,0.0,No Event,253.0
48,2023-08-18,30.5,18.8,15.4,Poor/Wet,0.0,No Event,122.0
49,2023-08-19,0.3,22.1,15.6,Good/Warm,0.0,No Event,75.0