SATFFING PROJECT

In [15]:
#Important libraries 
import pandas as pd
import numpy as np

In [10]:
#Import the 3 data sets from Met Eireann, the sets are clean and organized, the main task here is to merge them and create the conditionals that
#will determine how a good weather looks like to impact the hotel ocupancy
df_23 = pd.read_csv("dly1823_subset 2023.csv", skiprows=13)
df_24 = pd.read_csv("dly1823_subset2024.csv", skiprows=13 )
df_25 = pd.read_csv("dly1823_subset 2025.csv", skiprows=13)

#Combine into one master weather dataframe, 
df = pd.concat([df_23, df_24, df_25], ignore_index=True)


# Preview the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1065 entries, 0 to 1064
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1065 non-null   object
 1   ind     1065 non-null   int64
 2   rain    1065 non-null   float64
 3   ind.1   1065 non-null   int64
 4   maxt    1065 non-null   float64
 5   ind.2   1065 non-null   int64
 6   mint    1065 non-null   float64
 7   gmin    1065 non-null   object
 8   soil    1065 non-null   object
dtypes: float64(3), int64(3), object(3)
memory usage: 75.0+ KB

In [11]:
df.head

<bound method NDFrame.head of              date  ind  rain  ind.1  maxt  ind.2  mint  gmin soil
0        1-Jan-23    0   0.4      0   7.2      0   2.5   1.4
1        2-Jan-23    0   0.8      0  10.9      0   1.9  -1.7
2        3-Jan-23    0   0.6      0  14.4      1  -0.5  -4.4
3        4-Jan-23    0   0.2      0  12.9      0   9.4   8.2
4        5-Jan-23    0   1.8      0  13.7      0   9.6   6.4
...           ...  ...   ...    ...   ...    ...   ...   ...  ...
1060  26-nov-2025    0   0.8      0  14.6      1  -1.0  -4.5
1061  27-nov-2025    0   7.7      0  16.0      0   8.8   3.0
1062  28-nov-2025    0   1.7      0   9.2      0   6.5   3.2
1063  29-nov-2025    0   4.1      0   6.9      0   2.3  -3.9
1064  30-nov-2025    0   9.2      0  12.4      0   0.2  -5.0

[1065 rows x 9 columns]>

In [12]:
df_filtered = df [["date", "rain", "maxt", "mint"]] #Now I'll filter onyly the freatures that impact my model.
df_filtered.head(

       date  rain  maxt  mint
0  1-Jan-23   0.4   7.2   2.5
1  2-Jan-23   0.8  10.9   1.9
2  3-Jan-23   0.6  14.4  -0.5
3  4-Jan-23   0.2  12.9   9.4
4  5-Jan-23   1.8  13.7   9.6

In [17]:
conditions = [
    #Good/Warm: Less than 1mm rain AND 16C or warmer
    (df_filtered['rain'] < 1.0) & (df_filtered['maxt'] >= 16),
    
    #Dry/Cool: Less than 1mm rain AND cooler than 16C
    (df_filtered['rain'] < 1.0) & (df_filtered['maxt'] < 16),
    
    #Poor/Wet: 5mm+ of rain OR very cold (under 5C max)
    (df_filtered['rain'] >= 5.0) | (df_filtered['maxt'] < 5),
]

choices = ['Good/Warm', 'Dry/Cool', 'Poor/Wet']

# Apply the choices, everything else becomes 'Moderate/Changeable'
df_filtered['weather_quality'] = np.select(conditions, choices, default='Moderate/Changeable')


df_filtered.head()

C:\Users\NHLUJ\AppData\Local\Temp\ipykernel_23288\1755915190.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['weather_quality'] = np.select(conditions, choices, default='Moderate/Changeable')

       date  rain  maxt  mint      weather_quality
0  1-Jan-23   0.4   7.2   2.5             Dry/Cool
1  2-Jan-23   0.8  10.9   1.9             Dry/Cool
2  3-Jan-23   0.6  14.4  -0.5             Dry/Cool
3  4-Jan-23   0.2  12.9   9.4             Dry/Cool
4  5-Jan-23   1.8  13.7   9.6  Moderate/Changeable